### ISSUE TITLE
七濑胡桃menhera来源可能有误

### ISSUE THREAD

**Issue by SBBTD** [kallydev/emoticon#2]
来源应该是官方吧https://store.line.me/stickershop/product/7977628/zh-Hans
作者是joynet整个系列都是发在line store上的，可以用这个下载https://github.com/SBBTD/LineStickerDownloader

**Comment by kallydev** [comment]
作者信息确实有误，`ぽむ` 是 `Joynet` 所属在 `LINE` 进行贴图创作的画师。七濑胡桃的贴图包来源于 `LINE`，但出自 `ぽむ` 笔下，所以我认为把两者都写上比较合适。

**Comment by SBBTD** [comment]
嗯嗯，之前我也没仔细去查这位画师`ぽむ`，感谢回复
